/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package logins_application;
import java.awt.event.WindowEvent;
import javax.swing.JOptionPane;
import java.sql.Statement;
import java.sql.Connection;
import java.sql.DriverManager;
import javax.swing.JOptionPane;
import java.sql.ResultSet;
import java.sql.PreparedStatement;


/**
 *
 * @author Mr Eugene
 */
public class Questions extends javax.swing.JFrame {
    
    Connection conn = null;
    PreparedStatement ps = null;
    PreparedStatement ps2 = null;
    PreparedStatement ps3 = null;
    PreparedStatement ps4 = null;
    ResultSet rs = null;
    Statement S =null;
   
    /**
     * Creates new form Questions
     */
    public Questions() {
        initComponents();
        
        conn = Student_mySql.connectmysql();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        q1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Text_question1 = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        Text_question3 = new javax.swing.JTextArea();
        q3 = new javax.swing.JLabel();
        q2 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        Text_question2 = new javax.swing.JTextArea();
        q4 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        Text_question4 = new javax.swing.JTextArea();
        submit_btn = new javax.swing.JButton();
        exit_btn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 204, 204));
        setPreferredSize(new java.awt.Dimension(1366, 768));

        q1.setFont(new java.awt.Font("Calibri Light", 1, 18)); // NOI18N
        q1.setText("Q1.  How do you rate online class vs physical class ?");

        Text_question1.setColumns(20);
        Text_question1.setRows(5);
        jScrollPane1.setViewportView(Text_question1);

        Text_question3.setColumns(20);
        Text_question3.setRows(5);
        jScrollPane2.setViewportView(Text_question3);

        q3.setFont(new java.awt.Font("Calibri Light", 1, 18)); // NOI18N
        q3.setText("Q3. What do you prefer to use often ?");

        q2.setFont(new java.awt.Font("Calibri Light", 1, 18)); // NOI18N
        q2.setText("Q2. How do lecturer test how understable is the current session ?");

        Text_question2.setColumns(20);
        Text_question2.setRows(5);
        jScrollPane3.setViewportView(Text_question2);

        q4.setFont(new java.awt.Font("Calibri Light", 1, 18)); // NOI18N
        q4.setText("Q4. Suggest us what to improve in our system.");

        Text_question4.setColumns(20);
        Text_question4.setRows(5);
        jScrollPane4.setViewportView(Text_question4);

        submit_btn.setBackground(new java.awt.Color(110, 200, 123));
        submit_btn.setFont(new java.awt.Font("Trebuchet MS", 1, 36)); // NOI18N
        submit_btn.setText("SUBMIT");
        submit_btn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        submit_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submit_btnActionPerformed(evt);
            }
        });

        exit_btn.setBackground(new java.awt.Color(255, 0, 0));
        exit_btn.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        exit_btn.setForeground(new java.awt.Color(255, 255, 255));
        exit_btn.setText("EXIT");
        exit_btn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        exit_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exit_btnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(101, 101, 101)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 657, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(q1)
                        .addComponent(q2)
                        .addComponent(q3)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(36, 36, 36)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 650, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(q4)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(30, 30, 30)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 650, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 650, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 109, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(submit_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(79, 79, 79))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(exit_btn)
                        .addGap(14, 14, 14))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(q1)
                    .addComponent(exit_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(102, 102, 102)
                        .addComponent(submit_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(q2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(q3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(q4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    //getting elements from text box
    
    private void submit_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submit_btnActionPerformed
        // TODO add your handling code here:
        String question1 = Text_question1.getText();
        String question2 = Text_question2.getText();
        String question3 = Text_question3.getText();
        String question4 = Text_question4.getText();
        String q1_label = q1.getText();
        String q2_label = q2.getText();
        String q3_label = q3.getText();
        String q4_label = q4.getText();
        
        String test = "";
        if(question1.equals(test) || question2.equals(test) || question3.equals(test) || question4.equals(test)){
            JOptionPane.showMessageDialog(null,"Please answer all questions");
        }else{
               
            try{
                ps = conn.prepareStatement("INSERT INTO answers(question,answer) VALUES(?,?)");
                ps2 = conn.prepareStatement("INSERT INTO answers(question,answer) VALUES(?,?)");
                ps3 = conn.prepareStatement("INSERT INTO answers(question,answer) VALUES(?,?)");
                ps4 = conn.prepareStatement("INSERT INTO answers(question,answer) VALUES(?,?)");
                
                ps.setString(1,q1_label);
                ps.setString(2, question1);
                
                ps2.setString(1,q2_label);
                ps2.setString(2, question2);
                
                ps3.setString(1,q3_label);
                ps3.setString(2, question3);
                
                ps4.setString(1,q4_label);
                ps4.setString(2, question4);
                

                ps.executeUpdate();
                ps2.executeUpdate();
                ps3.executeUpdate();
                ps4.executeUpdate();
                
                JOptionPane.showMessageDialog(null,"Thank you!");
                
                Text_question1.setText(null);
                Text_question2.setText(null);
                Text_question3.setText(null);
                Text_question4.setText(null);
                
            }catch(Exception e){
                JOptionPane.showMessageDialog(null,e);
            }
        }
        
        
//        JOptionPane.showMessageDialog(null,"Success");
    }//GEN-LAST:event_submit_btnActionPerformed

    private void exit_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exit_btnActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_exit_btnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Questions.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Questions.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Questions.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Questions.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Questions().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea Text_question1;
    private javax.swing.JTextArea Text_question2;
    private javax.swing.JTextArea Text_question3;
    private javax.swing.JTextArea Text_question4;
    private javax.swing.JButton exit_btn;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JLabel q1;
    private javax.swing.JLabel q2;
    private javax.swing.JLabel q3;
    private javax.swing.JLabel q4;
    private javax.swing.JButton submit_btn;
    // End of variables declaration//GEN-END:variables

public void SystemExit(){
    WindowEvent winCloseing = new WindowEvent(this,WindowEvent.WINDOW_CLOSING);
}

}
